"""The table, and the one sentence somebody reads instead of the table.

The report is written for two readers. One is a contributor checking whether the compiler
lessons still work everywhere they are meant to, who wants the verdict line and nothing
else. The other is somebody who just hit an ImportError and is looking up their own row, who
wants the command they typed to be in the table so they can find it.

So the table has a column for how the Python was obtained, and the notes are under the table
rather than in it, and every unmeasured channel is listed by name instead of being left out.
"""

from __future__ import annotations

from .channels import CHANNELS, ELSEWHERE, Channel
from .question import WANTED, Answer, Survey

#: The module and all three functions.
FULL = "everything the lessons need"

#: The module imported, but not everything is on it. What an old Python looks like.
PARTIAL = "the module, not the functions"

#: The module is not there.
NONE = "no module"

#: Nothing was measured, for a reason that is about this machine and not about the channel.
UNKNOWN = "not measured"


def verdict(answer: Answer | None) -> str:
    if answer is None or answer.unreachable:
        return UNKNOWN
    if not answer.has_module:
        return NONE
    return FULL if answer.has_everything else PARTIAL


def cell(answer: Answer | None) -> str:
    """The result column, which says what happened rather than yes or no.

    A tick would be shorter and would hide the two rows that are the reason this table
    exists: the one where the module is there and the functions are not, and the one where a
    second package fixes it.
    """
    if answer is None:
        return "not measured here"
    if answer.unreachable:
        return f"not measured, {answer.unreachable}"
    if not answer.has_module:
        return answer.internal.split(":")[0]
    if answer.has_everything:
        return "yes, all three"
    return "module only, missing " + ", ".join(answer.missing)


def rows(survey: Survey, channels: list[Channel] | None = None) -> list[list[str]]:
    wanted = channels if channels is not None else CHANNELS
    made = []
    for one in wanted:
        answer = survey.answers.get(one.key)
        made.append(
            [
                one.name,
                f"`{one.how}`",
                answer.version if answer and answer.version else "",
                cell(answer),
            ]
        )
    return made


def table(survey: Survey, channels: list[Channel] | None = None) -> str:
    header = ["Channel", "How you get it", "Python", "`_testinternalcapi`"]
    lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    lines.extend("| " + " | ".join(one) + " |" for one in rows(survey, channels))
    return "\n".join(lines)


def counts(survey: Survey, channels: list[Channel] | None = None) -> dict[str, int]:
    wanted = channels if channels is not None else CHANNELS
    tally = {FULL: 0, PARTIAL: 0, NONE: 0, UNKNOWN: 0}
    for one in wanted:
        tally[verdict(survey.answers.get(one.key))] += 1
    return tally


def summary(survey: Survey, channels: list[Channel] | None = None) -> str:
    wanted = channels if channels is not None else CHANNELS
    tally = counts(survey, wanted)
    said = [f"{count} {name}" for name, count in tally.items() if count]
    return f"{len(wanted)} channels: " + ", ".join(said) + "."


def problems(survey: Survey, channels: list[Channel] | None = None) -> list[Channel]:
    """The channels where a reader would hit an ImportError, worst first.

    A channel that was not measured is not a problem. It is an unknown, and calling it a
    problem would make the count go down when somebody uninstalls Docker.
    """
    wanted = channels if channels is not None else CHANNELS
    order = {NONE: 0, PARTIAL: 1}
    found = [one for one in wanted if verdict(survey.answers.get(one.key)) in order]
    return sorted(found, key=lambda one: order[verdict(survey.answers[one.key])])


def markdown(survey: Survey, channels: list[Channel] | None = None) -> str:
    """The whole report, which is what gets committed."""
    wanted = channels if channels is not None else CHANNELS
    parts = [
        "# Does `_testinternalcapi` ship where readers get their Python",
        "",
        "Generated by `just build-dist`. Do not edit by hand, the change will be overwritten.",
        "",
        summary(survey, wanted),
        "",
        (
            "`_testinternalcapi` is the module that lets a reader run the CPython compiler "
            "one stage at a time without building anything. It is private, it has no "
            "compatibility guarantee, and the three functions the lessons use "
            f"({', '.join(f'`{one}`' for one in WANTED)}) only arrived in 3.12."
        ),
        "",
        table(survey, wanted),
        "",
    ]
    hard = problems(survey, wanted)
    if hard:
        parts += [
            "## Where a reader hits this",
            "",
        ]
        for one in hard:
            parts.append(f"**{one.name}.** {cell(survey.answers[one.key])}. {one.note}")
            parts.append("")
    unmeasured = [one for one in wanted if verdict(survey.answers.get(one.key)) == UNKNOWN]
    if unmeasured:
        parts += [
            "## Not measured, and what would measure it",
            "",
        ]
        for one in unmeasured:
            reason = ""
            answer = survey.answers.get(one.key)
            if one.kind != ELSEWHERE and answer and answer.unreachable:
                reason = f" This run could not: {answer.unreachable}."
            parts.append(f"**{one.name}.** {one.note}{reason}")
            parts.append("")
    parts += [
        "## Notes on the rest",
        "",
    ]
    for one in wanted:
        if one in hard or one in unmeasured:
            continue
        parts.append(f"**{one.name}.** {one.note}")
        parts.append("")
    parts.append(f"Containers were run as `{survey.machine}`.")
    return "\n".join(parts).rstrip("\n") + "\n"
