"""The committed answer: what the program printed, in which image, on which day.

The file is markdown because it is read by a person, in the repository and in the lesson,
and a JSON blob full of escaped newlines is not read by anybody. It is also parsed back,
which is why the shape is fixed and the file says at the top not to edit it by hand.

The one interesting decision here is that two recordings of the same experiment are not
required to be identical. A line the program marks with a leading `~` is a measurement, and
its number is compared by nobody. That is not a shortcut. The number this experiment prints
moves by two or three between runs of the same image on the same machine, because taking the
measurement is itself Python and runs the collector, and a check that demands byte equality
of a number like that fails once a fortnight for no reason. What happens next is somebody
deletes the check. So the label is compared and the number is not, and the real assertion,
the one that says the total did not move by two thousand, lives inside the program where it
runs against a live interpreter every time.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

from .experiments import MEASURED, Experiment

#: Where the recordings live, relative to the top of the repository.
RECORDINGS = Path("experiments") / "tier1"

#: The repository, worked out from where this file is. Everything that takes a root takes it
#: as an argument so the tests can point at a temporary directory, and this is the default for
#: the one caller that cannot pass one: a lesson's build.py, which wants to show a recording
#: without also being told where the repository is that it is already sitting inside.
REPOSITORY = Path(__file__).resolve().parents[4]

#: The line every generated file in this project carries, so nobody edits one by hand and
#: then loses the edit to the next build.
GENERATED = "Generated by `just build-tier1`. Do not edit by hand, the change will be overwritten."

#: The header fields, in the order they are written. Parsed back by prefix, which is why
#: they are here rather than spelled out twice.
FIELDS = ("Lesson", "Build", "Image", "Interpreter", "Recorded")

#: A fenced block, with the word after the fence and everything up to the closing fence.
FENCE = re.compile(r"^```(\w*)\n(.*?)\n```$", re.MULTILINE | re.DOTALL)


class Unreadable(ValueError):
    """A recording that is not one, or one this code cannot parse."""


def comparable(line: str) -> str:
    """The part of an output line that two runs have to agree on.

    A measured line agrees on its label. Everything else agrees on all of it.
    """
    if not line.startswith(MEASURED):
        return line
    head, colon, _ = line.rpartition(":")
    return head + colon if colon else line


@dataclass(frozen=True)
class Recording:
    """One run of one experiment, as it was committed."""

    slug: str
    title: str
    asks: str
    needs: str
    lesson: str
    build: str
    image: str
    interpreter: str
    recorded: str
    program: str
    output: list[str] = field(default_factory=list)

    @classmethod
    def path(cls, slug: str, root: Path | None = None) -> Path:
        return (root or REPOSITORY) / RECORDINGS / f"{slug}.md"

    def as_markdown(self) -> str:
        if "```" in self.program or any("```" in one for one in self.output):
            raise Unreadable(f"{self.slug}: a fence in the program or the output would break this")
        fields = "\n".join(
            f"- {name}: {value}"
            for name, value in zip(
                FIELDS,
                (self.lesson, self.build, self.image, self.interpreter, self.recorded),
                strict=True,
            )
        )
        printed = "\n".join(self.output)
        return (
            f"# {self.title}\n\n"
            f"{GENERATED}\n\n"
            f"{self.asks}\n\n"
            f"{fields}\n\n"
            f"Why this needs the {self.build} build: {self.needs}.\n\n"
            f"## The program\n\n"
            f"```python\n{self.program.rstrip()}\n```\n\n"
            f"## What it printed\n\n"
            f"```text\n{printed}\n```\n"
        )

    @classmethod
    def from_markdown(cls, slug: str, text: str) -> Recording:
        lines = text.splitlines()
        if not lines or not lines[0].startswith("# "):
            raise Unreadable(f"{slug}: the first line should be the title")
        found = {}
        for one in lines:
            for name in FIELDS:
                if one.startswith(f"- {name}: "):
                    found[name] = one.removeprefix(f"- {name}: ").strip()
        missing = [name for name in FIELDS if name not in found]
        if missing:
            raise Unreadable(f"{slug}: no {', '.join(missing)} line")
        blocks = FENCE.findall(text)
        if len(blocks) != 2:
            raise Unreadable(
                f"{slug}: expected a program block and an output block, got {len(blocks)}"
            )
        (_, program), (_, printed) = blocks

        # The question is the paragraph between the generated notice and the field list, and
        # the reason is the sentence after it. Both are recovered by looking for their
        # neighbours rather than by counting lines, so an extra blank line does not shift them.
        asks = ""
        for index, one in enumerate(lines):
            if one.strip() == GENERATED:
                asks = next((later for later in lines[index + 1 :] if later.strip()), "")
                break
        needs = ""
        for one in lines:
            if one.startswith("Why this needs the "):
                needs = one.partition(" build: ")[2].rstrip(".")
        return cls(
            slug=slug,
            title=lines[0].removeprefix("# ").strip(),
            asks=asks.strip(),
            needs=needs.strip(),
            lesson=found["Lesson"],
            build=found["Build"],
            image=found["Image"],
            interpreter=found["Interpreter"],
            recorded=found["Recorded"],
            program=program + "\n",
            output=printed.splitlines(),
        )

    @classmethod
    def load(cls, slug: str, root: Path | None = None) -> Recording:
        where = cls.path(slug, root)
        if not where.is_file():
            raise Unreadable(f"{slug}: nothing recorded yet, run `just build-tier1`")
        return cls.from_markdown(slug, where.read_text(encoding="utf-8"))

    def write(self, root: Path | None = None) -> Path:
        where = self.path(self.slug, root)
        where.parent.mkdir(parents=True, exist_ok=True)
        where.write_text(self.as_markdown(), encoding="utf-8")
        return where

    def problems(self, experiment: Experiment) -> list[str]:
        """Everything about this recording that no longer matches the experiment."""
        found = []
        if self.program.strip() != experiment.program.strip():
            found.append(
                f"{self.slug}: the recorded program is not the one in the catalogue, so the "
                f"output below it is the answer to a question nobody is asking now"
            )
        if self.build != experiment.build:
            found.append(
                f"{self.slug}: recorded on the {self.build} build, wants {experiment.build}"
            )
        if self.lesson != experiment.lesson:
            found.append(f"{self.slug}: recorded for {self.lesson}, belongs to {experiment.lesson}")
        if not self.output:
            found.append(f"{self.slug}: the program printed nothing")
        for one in self.output:
            if one.startswith(MEASURED) and ":" not in one:
                found.append(
                    f"{self.slug}: {one!r} is marked as a measurement and has no label, so "
                    f"there is nothing left to compare it by"
                )
        return found


def differences(old: Recording, new: Recording) -> list[str]:
    """What changed between the committed recording and a fresh run of the same experiment.

    Measured numbers are allowed to move. Everything else is not, and neither is the length
    of the output: a program that stopped printing its last line has stopped working, and
    reading that as "one line happened to differ" would let it through.
    """
    found = []
    if old.image != new.image:
        found.append(f"recorded against {old.image}, ran against {new.image}")
    was, now = old.interpreter.split()[0], new.interpreter.split()[0]
    if was != now:
        found.append(f"recorded on Python {was} and ran on {now}")
    if len(old.output) != len(new.output):
        found.append(f"printed {len(old.output)} lines before and {len(new.output)} now")
        return found
    for before, after in zip(old.output, new.output, strict=True):
        if comparable(before) != comparable(after):
            found.append(f"was {before!r} and is now {after!r}")
    return found


def show(slug: str, root: Path | None = None) -> str:
    """The recording as a lesson shows it, so nothing has to be copied into the prose.

    A lesson calls this from its builder and gets the question, the program and the output
    that a real debug build produced, with the image named underneath. The reader does not
    have to install anything to read it, and the reader who wants to check has the one
    command that would.
    """
    one = Recording.load(slug, root)
    printed = "\n".join(one.output)
    return (
        f"{one.asks}\n\n"
        f"```python\n{one.program.rstrip()}\n```\n\n"
        f"```text\n{printed}\n```\n\n"
        f"That ran on Python {one.interpreter.split()[0]} in the {one.build} build this project "
        f"publishes, which is `{one.image}`. You do not need that build to read the numbers, and "
        f"you do need it to produce them, which is why this is recorded rather than left as a "
        f"cell you run. If you want to watch it happen yourself, `docker run --rm -i {one.image} "
        f"python3 -` takes the program on standard input."
    )
