"""The committed transcript: what gdb printed, command by command, in which image.

Markdown, for the same reason `tier1` uses markdown. The file is read by a person, both in
the repository and in the lesson, and the lesson shows it a step at a time, so the shape has
to survive being parsed back rather than only being written out.

## The one real decision here

Two runs of the same session do not produce the same bytes, and they never will. Every
address is different because the kernel loads the program somewhere new each time, and the
process id is different because it is a different process. Those are compared with the
numbers taken out, which costs nothing: an address in a transcript is there to show that
there is an address, not to be that address.

Architecture is a harder problem and gets a harder answer. A backtrace on arm64 and a
backtrace on amd64 of the same stopped program disagree about more than numbers: different
frames survive, arm64 marks pointer authenticated returns with `[PAC]`, and the library
paths carry the target triple. Normalising all of that away would leave a transcript so
scrubbed that a real regression could hide in it. So a recording belongs to one
architecture, says so at the top, and is checked against a run on that architecture. There
is one file per architecture per session and neither is more real than the other.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

from .sessions import Session

#: Where the transcripts live, relative to the top of the repository.
RECORDINGS = Path("debugger")

#: The repository, worked out from where this file is. Everything that takes a root takes it
#: as an argument so the tests can point at a temporary directory, and this is the default
#: for the one caller that cannot pass one: a lesson's build.py, which wants to show a
#: transcript without also being told where the repository is that it already sits inside.
REPOSITORY = Path(__file__).resolve().parents[4]

#: The architectures this project publishes images for, and so the ones a transcript can be
#: recorded on. Written in Docker's spelling, which is what `--platform` wants.
ARCHES = ("amd64", "arm64")

#: The line every generated file in this project carries, so nobody edits one by hand and
#: then loses the edit to the next build.
GENERATED = "Generated by `just build-gdb`. Do not edit by hand, the change will be overwritten."

#: The header fields, in the order they are written. Parsed back by prefix, which is why
#: they are here rather than spelled out twice.
FIELDS = ("Lesson", "Build", "Arch", "Image", "Interpreter", "Debugger", "Recorded")

#: A fenced block, with the word after the fence and everything up to the closing fence.
FENCE = re.compile(r"^```(\w*)\n(.*?)\n```$", re.MULTILINE | re.DOTALL)

#: A step heading: the number, then the command in backticks.
HEADING = re.compile(r"^### (\d+)\. `(.*)`$", re.MULTILINE)

#: Everything two runs are allowed to disagree about. An address moves because the kernel
#: loads the program somewhere new, a process id moves because it is a different process,
#: and an offset into `_PyRuntime` moves when anything before it in that struct changes size.
#: None of the three is what a transcript is showing anybody.
VARIES = (
    (re.compile(r"0x[0-9a-fA-F]+"), "0xADDR"),
    (re.compile(r"\bprocess \d+"), "process N"),
    (re.compile(r"<(_PyRuntime)\+\d+>"), r"<\1+N>"),
)


class Unreadable(ValueError):
    """A transcript that is not one, or one this code cannot parse."""


def comparable(line: str) -> str:
    """The part of an output line two runs of the same session have to agree on."""
    for pattern, instead in VARIES:
        line = pattern.sub(instead, line)
    return line


@dataclass(frozen=True)
class Printed:
    """One command and what it printed, as it was committed."""

    command: str
    note: str
    output: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class Recording:
    """One run of one session on one architecture, as it was committed."""

    slug: str
    title: str
    asks: str
    needs: str
    lesson: str
    build: str
    arch: str
    image: str
    interpreter: str
    debugger: str
    recorded: str
    program: str
    steps: list[Printed] = field(default_factory=list)

    @classmethod
    def path(cls, slug: str, arch: str, root: Path | None = None) -> Path:
        return (root or REPOSITORY) / RECORDINGS / f"{slug}.{arch}.md"

    @classmethod
    def recorded_arches(cls, slug: str, root: Path | None = None) -> list[str]:
        """Which architectures this session has a transcript for, in a fixed order."""
        return [one for one in ARCHES if cls.path(slug, one, root).is_file()]

    def as_markdown(self) -> str:
        everything = [self.program, *(line for one in self.steps for line in one.output)]
        if any("```" in one for one in everything):
            raise Unreadable(f"{self.slug}: a fence in the program or the output would break this")
        fields = "\n".join(
            f"- {name}: {value}"
            for name, value in zip(
                FIELDS,
                (
                    self.lesson,
                    self.build,
                    self.arch,
                    self.image,
                    self.interpreter,
                    self.debugger,
                    self.recorded,
                ),
                strict=True,
            )
        )
        body = "".join(
            f"### {number}. `{one.command}`\n\n"
            f"{one.note}\n\n"
            f"```text\n" + "\n".join(one.output) + "\n```\n\n"
            for number, one in enumerate(self.steps, start=1)
        )
        return (
            f"# {self.title}\n\n"
            f"{GENERATED}\n\n"
            f"{self.asks}\n\n"
            f"{fields}\n\n"
            f"Why this needs the {self.build} build: {self.needs}.\n\n"
            f"## The program\n\n"
            f"```python\n{self.program.rstrip()}\n```\n\n"
            f"## The session\n\n"
            f"{body}".rstrip()
            + "\n"
        )

    @classmethod
    def from_markdown(cls, slug: str, text: str) -> Recording:
        lines = text.splitlines()
        if not lines or not lines[0].startswith("# "):
            raise Unreadable(f"{slug}: the first line should be the title")
        found = {}
        for one in lines:
            for name in FIELDS:
                if one.startswith(f"- {name}: "):
                    found[name] = one.removeprefix(f"- {name}: ").strip()
        missing = [name for name in FIELDS if name not in found]
        if missing:
            raise Unreadable(f"{slug}: no {', '.join(missing)} line")

        blocks = FENCE.findall(text)
        headings = HEADING.findall(text)
        if not blocks:
            raise Unreadable(f"{slug}: there is no program block")
        if len(blocks) != len(headings) + 1:
            raise Unreadable(
                f"{slug}: {len(headings)} command(s) and {len(blocks) - 1} output block(s), "
                f"which cannot both be right"
            )
        program = blocks[0][1]

        # The note is the paragraph between a step heading and its fence, recovered by
        # cutting the text at the headings rather than by counting lines, so an extra blank
        # line anywhere does not shift every step after it.
        pieces = HEADING.split(text)[1:]
        steps = []
        for index, (_, command) in enumerate(headings):
            chunk = pieces[index * 3 + 2]
            note = next((one for one in chunk.splitlines() if one.strip()), "")
            steps.append(
                Printed(command=command, note=note.strip(), output=blocks[index + 1][1].split("\n"))
            )

        asks = ""
        for index, one in enumerate(lines):
            if one.strip() == GENERATED:
                asks = next((later for later in lines[index + 1 :] if later.strip()), "")
                break
        needs = ""
        for one in lines:
            if one.startswith("Why this needs the "):
                needs = one.partition(" build: ")[2].rstrip(".")
        return cls(
            slug=slug,
            title=lines[0].removeprefix("# ").strip(),
            asks=asks.strip(),
            needs=needs.strip(),
            lesson=found["Lesson"],
            build=found["Build"],
            arch=found["Arch"],
            image=found["Image"],
            interpreter=found["Interpreter"],
            debugger=found["Debugger"],
            recorded=found["Recorded"],
            program=program + "\n",
            steps=steps,
        )

    @classmethod
    def load(cls, slug: str, arch: str, root: Path | None = None) -> Recording:
        where = cls.path(slug, arch, root)
        if not where.is_file():
            raise Unreadable(f"{slug}: nothing recorded on {arch} yet, run `just build-gdb`")
        return cls.from_markdown(slug, where.read_text(encoding="utf-8"))

    def write(self, root: Path | None = None) -> Path:
        where = self.path(self.slug, self.arch, root)
        where.parent.mkdir(parents=True, exist_ok=True)
        where.write_text(self.as_markdown(), encoding="utf-8")
        return where

    def problems(self, session: Session) -> list[str]:
        """Everything about this transcript that no longer matches the session above it."""
        found = []
        if self.program.strip() != session.program.strip():
            found.append(
                f"{self.slug}: the recorded program is not the one in the catalogue, so the "
                f"transcript below it is the answer to a question nobody is asking now"
            )
        if self.build != session.build:
            found.append(f"{self.slug}: recorded on the {self.build} build, wants {session.build}")
        if self.lesson != session.lesson:
            found.append(f"{self.slug}: recorded for {self.lesson}, belongs to {session.lesson}")
        if self.arch not in ARCHES:
            found.append(f"{self.slug}: {self.arch!r} is not an architecture this project builds")
        recorded = [one.command for one in self.steps]
        if recorded != session.commands():
            found.append(
                f"{self.slug}: the recorded commands are not the ones in the catalogue, so "
                f"somebody changed the script and left the old output underneath it"
            )
            return found
        for one, step in zip(self.steps, session.script, strict=True):
            if one.note != step.note:
                found.append(f"{self.slug}: the note on `{one.command}` has been edited by hand")
        return found


def differences(old: Recording, new: Recording) -> list[str]:
    """What changed between the committed transcript and a fresh run of the same session.

    Addresses and process ids are allowed to move and nothing else is, including the number
    of lines a command printed. A command that stopped printing its last line has stopped
    working, and reading that as "one line happened to differ" would wave it through.
    """
    found = []
    if old.arch != new.arch:
        return [f"recorded on {old.arch}, ran on {new.arch}, which are not comparable"]
    if old.image != new.image:
        found.append(f"recorded against {old.image}, ran against {new.image}")
    was, now = old.interpreter.split()[0], new.interpreter.split()[0]
    if was != now:
        found.append(f"recorded on Python {was}, ran on Python {now}")
    if old.debugger != new.debugger:
        found.append(f"recorded with {old.debugger}, ran with {new.debugger}")
    for before, after in zip(old.steps, new.steps, strict=False):
        if before.command != after.command:
            found.append(f"`{before.command}` is now `{after.command}`")
            continue
        if len(before.output) != len(after.output):
            found.append(
                f"`{before.command}` printed {len(before.output)} line(s) and now prints "
                f"{len(after.output)}"
            )
            continue
        for line, fresh in zip(before.output, after.output, strict=True):
            if comparable(line) != comparable(fresh):
                found.append(f"`{before.command}`: {line!r} is now {fresh!r}")
    if len(old.steps) != len(new.steps):
        found.append(f"{len(old.steps)} command(s) recorded, {len(new.steps)} ran")
    return found


def show(
    slug: str,
    arch: str,
    root: Path | None = None,
    first: int = 1,
    last: int | None = None,
) -> str:
    """A run of steps from one transcript, as markdown, numbered as they really are.

    `first` and `last` are the step numbers a reader sees, counting from one and including
    both ends. They exist so a lesson can put three paragraphs of its own between step five
    and step six instead of dropping nine commands on the page at once, and the numbering
    keeps running across the gap so the reader can tell it is still the same session.
    """
    found = Recording.load(slug, arch, root)
    stop = len(found.steps) if last is None else last
    if not 1 <= first <= stop <= len(found.steps):
        raise Unreadable(
            f"{slug}: asked for steps {first} to {stop} and there are {len(found.steps)}"
        )
    body = "".join(
        f"**{number}. `{one.command}`**\n\n"
        f"{one.note}\n\n"
        f"```text\n" + "\n".join(one.output) + "\n```\n\n"
        for number, one in enumerate(found.steps[first - 1 : stop], start=first)
    )
    return body.rstrip()


def steps_of(slug: str, arch: str, root: Path | None = None) -> list[Printed]:
    """Every step of one transcript, for a lesson that wants to lay them out itself."""
    return Recording.load(slug, arch, root).steps


def program_of(slug: str, arch: str, root: Path | None = None) -> str:
    """The program the session was run against, so a lesson shows it rather than retyping it.

    Retyping it is the failure worth avoiding here. Every line number in the transcript below
    is a line number in this program, so a copy that drifts by one blank line makes the whole
    session point at the wrong lines and nothing catches it.
    """
    return Recording.load(slug, arch, root).program.rstrip()
