"""Turning two runs into a table somebody can read.

The interesting column is not "did it work in the browser" on its own. It is the pair. A
check that fails in both places is a check that is wrong, or a surface that went away in
this version of Python, and either way it is our problem rather than WebAssembly's. A check
that works natively and fails in the browser is the actual finding.

The output is markdown because it gets committed next to the results and read on GitHub.
"""

from __future__ import annotations

from .checks import CHECKS, Check
from .result import FATAL, OK, RAISED, SKIPPED, Outcome, Run

#: What the pair of statuses means, in the order the report should worry about them.
BOTH_FINE = "works in both"
ONLY_NATIVE = "works natively, not in the browser"
ONLY_BROWSER = "works in the browser, not natively"
NEITHER = "fails in both"

MARKS = {OK: "yes", RAISED: "raises", FATAL: "kills the runtime", SKIPPED: "not reached"}


def verdict(native: Outcome, browser: Outcome) -> str:
    """One sentence about what the two runs together say."""
    if native.worked and browser.worked:
        return BOTH_FINE
    if native.worked:
        return ONLY_NATIVE
    if browser.worked:
        return ONLY_BROWSER
    return NEITHER


def regressions(native: Run, browser: Run, checks: list[Check] | None = None) -> list[Check]:
    """The blocking checks that work here and not there, which is what CI should fail on."""
    found = []
    for check in checks if checks is not None else CHECKS:
        if not check.blocking:
            continue
        here = native.outcomes.get(check.key)
        there = browser.outcomes.get(check.key)
        if here is None or there is None:
            continue
        if verdict(here, there) == ONLY_NATIVE:
            found.append(check)
    return found


def differences(
    native: Run, browser: Run, checks: list[Check] | None = None
) -> list[tuple[Check, object, object]]:
    """Checks that worked in both places and came back with different answers.

    These are not failures. They are the places where the two builds really are different
    machines, and a lesson that asserts one of these numbers is teaching the build rather
    than the language.
    """
    found = []
    for check in checks if checks is not None else CHECKS:
        here = native.outcomes.get(check.key)
        there = browser.outcomes.get(check.key)
        if here is None or there is None or not (here.worked and there.worked):
            continue
        if here.value != there.value:
            found.append((check, here.value, there.value))
    return found


def _cell(outcome: Outcome | None) -> str:
    if outcome is None:
        return "not run"
    mark = MARKS.get(outcome.status, outcome.status)
    if outcome.worked or not outcome.error:
        return mark
    return f"{mark}, {outcome.error}"


def table(native: Run, browser: Run, checks: list[Check] | None = None) -> str:
    """The matrix, one row per check."""
    here_column = f"{native.python} native"
    there_column = f"{browser.python} WebAssembly"
    rows = [
        f"| Check | Needed for | {here_column} | {there_column} |",
        "| --- | --- | --- | --- |",
    ]
    for check in checks if checks is not None else CHECKS:
        here = _cell(native.outcomes.get(check.key))
        there = _cell(browser.outcomes.get(check.key))
        needed = check.weight + (", known gap" if check.accepted else "")
        rows.append(f"| {check.question} | {needed} | {here} | {there} |")
    return "\n".join(rows)


def summary(native: Run, browser: Run, checks: list[Check] | None = None) -> str:
    """A line of counts, so the table has something to be read against."""
    wanted = checks if checks is not None else CHECKS
    counts = {BOTH_FINE: 0, ONLY_NATIVE: 0, ONLY_BROWSER: 0, NEITHER: 0}
    for check in wanted:
        here = native.outcomes.get(check.key)
        there = browser.outcomes.get(check.key)
        if here is None or there is None:
            continue
        counts[verdict(here, there)] += 1
    parts = [f"{count} {name}" for name, count in counts.items() if count]
    blocked = len(regressions(native, browser, wanted))
    tail = f", {blocked} of them blocking" if blocked else ""
    return f"{len(wanted)} checks: " + ", ".join(parts) + tail + "."


def markdown(native: Run, browser: Run, checks: list[Check] | None = None) -> str:
    """The whole report, ready to be written to a file."""
    # Written as one output line, in pieces, because the project keeps prose to one
    # sentence per line and the line length rule still applies to the source.
    megabytes = browser.payload_bytes / 1_000_000
    intro = (
        f"Generated by `wasmprobe report`. "
        f"Native run on CPython {native.python}, "
        f"WebAssembly run on Pyodide with CPython {browser.python}, "
        f"which booted in {browser.seconds:.1f} seconds "
        f"off a local disk after {megabytes:.1f} MB of runtime and standard library."
    )
    lines = [
        "# What works under Pyodide",
        "",
        intro,
        "",
        summary(native, browser, checks),
        "",
        table(native, browser, checks),
        "",
        "## What a failure would cost",
        "",
    ]
    for check in checks if checks is not None else CHECKS:
        lines.append(f"**{check.question}.** {check.costs}")
        lines.append("")
    apart = differences(native, browser, checks)
    if apart:
        lines.append("## Where the two answers differ")
        lines.append("")
        lines.append("Both runtimes answered these, and answered them differently.")
        lines.append("")
        lines.append("| Check | Native | WebAssembly |")
        lines.append("| --- | --- | --- |")
        for check, here, there in apart:
            lines.append(f"| {check.question} | `{here}` | `{there}` |")
        lines.append("")
    known = [check for check in (checks if checks is not None else CHECKS) if check.accepted]
    if known:
        lines.append("## Known gaps, and what we do instead")
        lines.append("")
        for check in known:
            lines.append(f"**{check.question}.** {check.accepted}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"
